/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYROODOUBLECBSHAPE
#define MYROODOUBLECBSHAPE
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
//#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
//#include "RooAbsCategory.h"
using namespace std; 
class RooMyPDF_BW : public RooAbsPdf {
public:
  RooMyPDF_BW() {} ; 
  RooMyPDF_BW(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _gamma);
  RooMyPDF_BW(const RooMyPDF_BW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyPDF_BW(*this,newname); 

  }
  inline virtual ~RooMyPDF_BW() { }

  //Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  //Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy gamma ;
  
  Double_t evaluate() const ;

//private:

// ClassDef(RooMyPDF_BW,1) // Your description goes here...
};
 
#endif
